name: Release Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  analyze-release:
    runs-on: ubuntu-latest
    container:
      image: mostfarwag/release:3  # غيرها باسم الـ image بتاعك
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Release Analyzer
        env:
          REPO_URL: ${{ github.repositoryUrl }}
        run: |
          # الـ container بيشتغل تلقائيًا بالـ CMD بتاع الـ Dockerfile
          # بنستنى الـ container يكمل ونجيب الـ output
          sleep 10  # نستنى الـ script يكمل
          cat /app/new_tag.txt || echo "No new tag generated"

      - name: Debug Output
        run: |
          echo "Workflow completed. Check the logs above for the new tag or errors."
