name: Release Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # صلاحية لتعديل الريبو ورفع الـ tags
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # عشان نجيب تاريخ الـ Git كامل بما فيه الـ tags

      - name: Build and Run Docker Image
        run: docker run -d  -p 5000:5000 --name release-container  mostfarwag/release:3
      run: |
          docker run -d --name release-container \
            -v $(pwd):/app \
            -p 5000:5000 \
             mostfarwag/release:3 \
            -e REPO_URL=https://github.com/${{ github.repository }}.git
      - name: Wait for API to Start
        run: |
          # انتظار حتى يبدأ الـ API في الاستماع على المنفذ 5000
          until docker exec release-container bash -c "nc -z localhost 5000"; do
            echo "Waiting for API to start..."
            sleep 1
          done
          echo "API is ready!"

      - name: Retrieve the new tag from the container
        run: |
          NEW_TAG=$(docker exec release-container bash -c "cat /app/new_tag.txt")
          echo "New Tag: $NEW_TAG"

      - name: Create and Push Tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Stop Docker Container
        if: always()
        run: |
          docker stop release-container || true
          docker rm release-container || true
