name: Release Analysis

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ุฅุนุทุงุก ุตูุงุญูุฉ ูุชุนุฏูู ุงูุฑูุจู ูุฑูุน ุงูู tags
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ุฌูุจ ุชุงุฑูุฎ Git ูุงูู ุจูุง ููู ุงูู tags

      - name: Run Docker Image
        run: |
          echo "๐ ุชุดุบูู ุงูุญุงููุฉ..."
          docker run -d --name release-container \
            -p 5000:5000 \
            -e REPO_URL=https://github.com/${{ github.repository }}.git \
            mostfarwag/release:3

          echo "โณ ุงูุชุธุงุฑ ุจุฏุก ุชุดุบูู ุงูุญุงููุฉ..."
          sleep 5  # ุงูุงูุชุธุงุฑ ููููุงู ูุชุฌูุจ ุฃุฎุทุงุก ุจุฏุก ุงูุชุดุบูู
          
          # ุงูุชุญูู ูู ุฃู ุงูุญุงููุฉ ุจุฏุฃุช ุจูุฌุงุญ
          if [ "$(docker ps -q -f name=release-container)" == "" ]; then
            echo "โ ูุดู ูู ุชุดุบูู ุงูุญุงููุฉ! ุชุญูู ูู ุงูู Dockerfile ุฃู ุงูู Image."
            docker logs release-container || true
            exit 1
          fi

      - name: Wait for API and Script to Complete
        run: |
          echo "๐ข ูุชุงุจุนุฉ ููุฌุงุช ุงูุญุงููุฉ..."
          docker logs -f release-container &
          CONTAINER_PID=$!
          
          # ุงูุชุญูู ูู ุฃู ุงูุญุงููุฉ ูุง ุชุฒุงู ุชุนูู ูุจู ุงูุชุธุงุฑูุง
          if [ "$(docker ps -q -f name=release-container)" == "" ]; then
            echo "โ ุงูุญุงููุฉ ุชูููุช ูุฌุฃุฉ! ุนุฑุถ ุงูููุฌุงุช ุซู ุงูุฅููุงุก."
            docker logs release-container || true
            exit 1
          fi

          echo "โณ ุงูุชุธุงุฑ ุงูุชูุงุก ุงูุนูููุฉ ุฏุงุฎู ุงูุญุงููุฉ..."
          docker wait release-container || true
          
          # ูุชู ุนูููุฉ ูุชุงุจุนุฉ ุงูููุฌุงุช ูุชุฌูุจ ุงููุดุงูู
          kill $CONTAINER_PID || true

      - name: Stop Docker Container
        if: always()
        run: |
          echo "๐ ุฅููุงู ุงูุญุงููุฉ..."
          docker stop release-container || true
          docker rm release-container || true
