name: Release Analysis

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # صلاحية لتعديل الريبو ورفع الـ tags
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # عشان نجيب تاريخ الـ Git كامل بما فيه الـ tags

      - name: Run Docker Image
        run: docker run  -d --name release-container -e REPO_URL=https://github.com/${{ github.repository }}.git release-analyzer

      - name: Wait for API and Script to Complete
        run: |
          docker logs -f release-container
          

      - name: Stop Docker Container
        if: always()
        run: |
          docker stop release-container || true
          docker rm release-container || true
