name: Call Release Analysis

on:
  push:
    branches:
      - main

jobs:
  call_release_analysis:
    uses: Moustafa-Yousef/ReleaseManagement/.github/workflows/release_analysis.yml@main  # ✅ استدعاء الـ workflow الأساسي
    permissions:
      contents: write
    secrets:
      PAT: ${{ secrets.PAT }}  # ✅ مرر الـ token لاستخدامه في جلب الريبو الأساسي
