name: Release Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  analyze-release:
    runs-on: ubuntu-latest
    steps:  # شيلنا الـ container وهنستخدم docker run
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Docker Image and Capture Output
        id: run-analyzer
        env:
          REPO_URL: ${{ github.repositoryUrl }}
        run: |
          # نشغل الـ image ونحفظ الـ output كله
          docker run --name release-container -p 5000:5000-e REPO_URL=$REPO_URL mostfarwag/release:3 > output.log 2>&1
          # نجرب نجيب الـ NEW_TAG من الملف
          docker cp release-container:/app/new_tag.txt ./new_tag.txt || echo "Failed to copy new_tag.txt"
          NEW_TAG=$(cat ./new_tag.txt 2>/dev/null || echo "")
          # لو الملف مش موجود، نحاول نجيب الـ tag من الـ output
          if [ -z "$NEW_TAG" ]; then
            NEW_TAG=$(grep "New tag created and pushed" output.log | awk '{print $NF}' || echo "No new tag generated")
          fi
          if [ -z "$NEW_TAG" ] || [ "$NEW_TAG" = "No new tag generated" ]; then
            echo "Error: Could not generate NEW_TAG"
            cat output.log  # نطبع الـ logs كلها للتشخيص
            exit 1
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "Captured NEW_TAG: $NEW_TAG"

      - name: Create and Push Git Tag
        run: |
          NEW_TAG="${{ steps.run-analyzer.outputs.NEW_TAG }}"
          if [ "$NEW_TAG" != "No new tag generated" ]; then
            git tag "$NEW_TAG"
            git push origin "$NEW_TAG" || echo "Error: Failed to push tag"
          else
            echo "Skipping tag creation: No valid NEW_TAG generated"
          fi

      - name: Debug Output
        run: |
          echo "Workflow completed. New tag: ${{ steps.run-analyzer.outputs.NEW_TAG }}"
