name: Release Analysis

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Docker Image
        run: |
          docker run -d --name release-container \
            -p 5000:5000 \
            -e REPO_URL=https://github.com/${{ github.repository }}.git \
            mostfarwag/release:4

      - name: Wait for API and Script to Complete
        id: wait-for-container
        run: |
          docker logs -f release-container > container_logs.txt
          docker wait release-container
          # عرض السجلات للتحقق
          cat container_logs.txt
          # استخراج التاج الجديد
          NEW_TAG=$(grep "New tag created and pushed" container_logs.txt | awk '{print $NF}')
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Check if NEW_TAG is empty
        run: |
          if [ -z "${{ env.NEW_TAG }}" ]; then
            echo "Error: NEW_TAG is empty. Exiting." && exit 1
          fi

      - name: Stop Docker Container
        if: always()
        run: |
          docker stop release-container || true
          docker rm release-container || true

      - name: Configure Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Create and Push New Tag Directly
        run: |
          echo "Old tag from Docker: $
