name: Release Analysis

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  analyze-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Docker Image and Capture NEW_TAG
        id: run-analyzer
        env:
          REPO_URL: ${{ github.repositoryUrl }}
        run: |
          docker run --name release-container -e REPO_URL=$REPO_URL mostfarwag/release:3
          docker cp release-container:/app/new_tag.txt ./new_tag.txt || echo "Failed to copy new_tag.txt"
          NEW_TAG=$(cat ./new_tag.txt 2>/dev/null || echo "")
          if [ -z "$NEW_TAG" ]; then
            echo "Error: NEW_TAG is empty or not generated"
            exit 1
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "Captured NEW_TAG: $NEW_TAG"

      - name: Create and Push Git Tag
        run: |
          NEW_TAG=${{ steps.run-analyzer.outputs.NEW_TAG }}
          git tag $NEW_TAG
          git push origin $NEW_TAG || echo "Error: Failed to push tag"

      - name: Debug Output
        run: |
          echo "Workflow completed. New tag: ${{ steps.run-analyzer.outputs.NEW_TAG }}"
