name: Call Release Analysis

on:
  push:
    branches:
      - main

jobs:
  run_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        run: docker pull mostfarwag/release:latest
      
      - name: Run Docker Container
        run: docker run --rm mostfarwag/release:latest


