name: Use Release Analysis

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: Moustafa-Yousef/ReleaseManagement/.github/workflows/release_analysis.yml@main  # 👈 استدعاء الأكشن من الريبو الأساسي
    with:
      branch: "main"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
