name: Release Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  analyze-release:
    runs-on: ubuntu-latest
    container:
      image: mostfarwag/release:3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Release Analyzer
        id: run-analyzer
        env:
          REPO_URL: ${{ github.repositoryUrl }}
        run: |
          sleep 10
          NEW_TAG=$(cat /app/new_tag.txt 2>/dev/null || echo "No new tag generated")
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          cat /app/new_tag.txt || echo "No new tag generated"
          docker ps

      - name: Create and Push Git Tag
        run: |
          NEW_TAG="${{ steps.run-analyzer.outputs.NEW_TAG }}"
          if [ "$NEW_TAG" != "No new tag generated" ]; then
            git tag "$NEW_TAG"
            git push origin "$NEW_TAG" || echo "Error: Failed to push tag"
          else
            echo "Skipping tag creation: No valid NEW_TAG generated"
          fi

      - name: Debug Output
        run: |
          echo "Workflow completed. New tag: ${{ steps.run-analyzer.outputs.NEW_TAG }}"
